### ISSUE TITLE
page 2: put header "vermogensbeheer" higher

### ISSUE THREAD

**Issue by jvsoest** [MaastrichtU-BISS/ibi-project#19]
The header VERMOGENSBEHEER and the following sub header could be placed at the same height as the chart on the right hand side of the page.

**Comment by sabaturgay** [comment]
Closed with cd8042e36e1ebcc72f7827416c1cf2c1bfd25fc5

**Comment by jvsoest** [comment]
![image](https://user-images.githubusercontent.com/2477683/139743887-134aa39b-f290-4a5e-aa72-a140922672eb.png)
The left and right height are not equal, also the divider (between left and right) should be on the same height.

**Comment by sabaturgay** [comment]
They have the same top space. But the header has some margin as a component. So I decreased its top space. 
<img width="952" alt="Screenshot 2021-11-02 at 10 12 24" src="https://user-images.githubusercontent.com/22500853/139801717-00ed947c-3eea-49a8-8cdb-54f2e8875767.png"
<img width="937" alt="Screenshot 2021-11-02 at 10 16 08" src="https://user-images.githubusercontent.com/22500853/139802139-2a33a577-5c88-4577-a28e-7df5d620b7c6.png">
>

**Comment by sabaturgay** [comment]
They have the same top space. But the header has some margin as a component. So I decreased its top space. 
<img width="873" alt="Screenshot 2021-11-02 at 10 17 35" src="https://user-images.githubusercontent.com/22500853/139802344-20f6ae33-329a-4605-869f-6a38ca397ecd.png">
<img width="937" alt="Screenshot 2021-11-02 at 10 16 08" src="https://user-images.githubusercontent.com/22500853/139802139-2a33a577-5c88-4577-a28e-7df5d620b7c6.png">
>
