### ISSUE TITLE
Old template is shown

### ISSUE THREAD

**Issue by jvsoest** [MaastrichtU-BISS/ibi-project#2]
Old template (or elements of tempalte) are shown.
Some remarks from IBI:

o	logo moves to old position
o	text uitvoeringskosten is missing
o	piechart2 is missing, 
o	speedometer0
    	text is small
    	speedometer is different
    	legend for now next to chart instead of above, vertical vs. horizontal

**Comment by sabaturgay** [comment]
> Old template (or elements of tempalte) are shown. Some remarks from IBI:
> 
> o logo moves to old position o text uitvoeringskosten is missing o piechart2 is missing, o speedometer0  text is small  speedometer is different  legend for now next to chart instead of above, vertical vs. horizontal

#3 is now fixed. Could you add more info (images) to clarify, please?

**Comment by jvsoest** [comment]
If I'm using the "Create charts" button, the layout moves. It might be that I'm using an old JSON file. But I'm not sure if that's causing the issue (i've used the assets/example-data.json file)

**Comment by sabaturgay** [comment]
I think it was because of the old JSON data. Could you try again, please?

**Comment by jvsoest** [comment]
Indeed resolved by f95ea2de67dcfc7bbcb3c580c20c8d0be9252b94
