### ISSUE TITLE
page 3: pensioenbeheer too high on page

### ISSUE THREAD

**Issue by jvsoest** [MaastrichtU-BISS/ibi-project#21]
ii)	the header PENSIOENBEHEER and the following sub header and text are placed too high while there is enough space at the bottom of the page. It should be the same as on the other pages and as the sub header on the lefthand-side

**Comment by sabaturgay** [comment]
Closed with cd8042e36e1ebcc72f7827416c1cf2c1bfd25fc5

**Comment by jvsoest** [comment]
![image](https://user-images.githubusercontent.com/2477683/139744207-1ea12e3d-d706-42d9-a6d1-cfd94465378d.png)
I think it's just a few pixels off (lowering the left side?)
