### ISSUE TITLE
page 4: align left-hand side at top page

### ISSUE THREAD

**Issue by jvsoest** [MaastrichtU-BISS/ibi-project#23]
i)	the elements on left-hand and right-hand side do not align at the top. either align top or align at body text.

**Comment by sabaturgay** [comment]
fixed with cd8042e36e1ebcc72f7827416c1cf2c1bfd25fc5

**Comment by sabaturgay** [comment]
fixed with cd8042e36e1ebcc72f7827416c1cf2c1bfd25fc5

**Comment by jvsoest** [comment]
![image](https://user-images.githubusercontent.com/2477683/139744355-513a5775-26b3-4064-bdcd-b48b1a6b0b48.png)
Please double check the heights of left and right
