### ISSUE TITLE
IBI logo incorrect

### ISSUE THREAD

**Issue by jvsoest** [MaastrichtU-BISS/ibi-project#34]
By using the logo as SVG, we are dependent on whether someone has the font locally installed, change to PNG to make it stable

![image](https://user-images.githubusercontent.com/2477683/140534909-5cd8b470-c3fb-47ed-8f2e-a80dc2d6e89d.png)

**Comment by jvsoest** [comment]
![ibi-logo](https://user-images.githubusercontent.com/2477683/140535137-31f0f9ef-47d6-47cd-b763-096d01f60501.png)

**Comment by sabaturgay** [comment]
fixed with dfd0b4cf27a93a756746885eb1551e7119e2e1e4
