### ISSUE TITLE
The text in the text blocks is sometimes justified as desired, but mostly not

### ISSUE THREAD

**Issue by jvsoest** [MaastrichtU-BISS/ibi-project#8]
@sabaturgay do you know what they mean with this title?

**Comment by sabaturgay** [comment]
I do not know what they mean

**Comment by jvsoest** [comment]
Apparently they were talking about "text-align: justify" in the CSS. Some places had this before (but I cannot find it). Will ask if they have a preference (everything or nothing).

**Comment by jvsoest** [comment]
See commit above
